import os

class Config:
    ORACLE_USER=''
    ORACLE_PASSWORD=''
    ORACLE_DSN=''
    SECRET_KEY=''
    UPLOAD_FOLDER='uploads'
    ALLOWED_EXTENSIONS = ('csv')
    CLOUDERA_DSN_CA_14487 = 'DATA_CONNECTION_CA_14487'
    CLOUDERA_DSN_US_DI_12746 = 'DATA_CONNECTION_US_DI_12746'
    CLOUDERA_DSN_US_DOM_12582 = 'DATA_CONNECTION_US_DOM_12582'
